#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 18:52:52 2017

@author: AlydaHuerta
"""

#have arm go to Molly home position

import arm_class
import inverseKinematics
import TowelAssistance
from me212cv.msg import GlovePos
import std_msgs.msg

arm=arm_class()

rospy.init_node('arm_controller')

# Glove position handler
global glove_inframe, glove_position
glove_sub = rospy.Subscriber('/glove_position',GlovePos, glove_callback)

global task
task_sub = rospy.Subcriber('/command', std_msgs.msg.String, task_callback)

while not task=='finished'

    if task== 'drawer task complete': #has to be done before human moves in front of drawer
    	task='0'
    	homeMatrix=ikDrawer.getArrayToGoHome() #Gets matrix of motor angles as steps to the home position
    	rowsAndColumns=homeMatrix.size #finds how many rows and columns in the matrix
    		for i in range (0, rowsAndColumns[0]-1): #calls inverse kinematics function for each row of the matrix
    			angleVector=ikDrawer.ik(homeVector[i,:])
    			arm.joint1_cmd(angleVector[0])
    			arm.joint2_cmd(angleVector[1])
    			arm.joint3_cmd(angleVector[2])