#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 06:07:16 2017

@author: AlydaHuerta
"""
#import math 
import scipy.io


#this script has the angles needed for the garment task

#math.radians()

#def GarmentHomePositionAngles():
angles = scipy.io.loadmat('outputangles_garmenthomeposition.mat')
print (angles)
    #return angles